/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WeanWatch;

import java.awt.Dimension;

import WeanWatch.controller.LoginCtrl;
import WeanWatch.controller.RootCtrl;
import WeanWatch.model.PatientHandler;
import WeanWatch.model.Personnel;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import java.io.IOException;


public class App extends Application {

    // Store the primary scene
    private Stage weanStage;

    public static void main(String[] args) {
        // Start loading the patients form the PDMS
        PatientHandler.getInstance().getPatients();
        // Launch JavaFX
        launch(args); 
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Store the primary stage
        this.weanStage = primaryStage;
        // Show the login screen
        this.userLogOutCallback();
        // Show the stage
        primaryStage.show();
    }

    protected void userLoginCallback(Personnel user) {
        // Get the scene size
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        // Create a FXML loader
        FXMLLoader loader = new FXMLLoader();
        // Set the location of the login view
		loader.setLocation(App.class.getClassLoader().getResource("view/RootView.fxml"));
        // Try loading the borderpane
        try {
            // Load the borderpane
            BorderPane rootView = (BorderPane) loader.load();
            // Set the scene
            this.weanStage.setScene(new Scene(rootView, screenSize.getWidth(), screenSize.getHeight()));
            // Get the controller
            RootCtrl rootCtrl = loader.getController();
            // Set the logout callback
            rootCtrl.setLogOutCallback(() -> {
                userLogOutCallback();
            });
            // Set the personnel
            rootCtrl.setPersonnel(user);
        } catch (IOException e) {
            System.err.println("Failed to display navigation screen.");
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("Unhandled exception.");
            e.printStackTrace();
        }
    }

    protected void userLogOutCallback() {
        // Get the scene size
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        // Create a FXML loader
        FXMLLoader loader = new FXMLLoader();
        // Set the location of the login view
		loader.setLocation(App.class.getClassLoader().getResource("view/LoginView.fxml"));
        // Try loading the borderpane
        try {
            // Load the borderpane
            BorderPane loginView = (BorderPane) loader.load();
            // Set the scene
            this.weanStage.setScene(new Scene(loginView, screenSize.getWidth(), screenSize.getHeight()));
            // Get the controller
            LoginCtrl loginCtrl = loader.getController();
            // Set the login callback
            loginCtrl.setLoginCallback((Personnel user) -> {
                userLoginCallback(user);
            });
        } catch (IOException e) {
            System.err.println("Failed to display login screen.");
            e.printStackTrace();
        } catch (Exception e) {
            System.err.println("Unhandled exception.");
            e.printStackTrace();
        }
    }
}
