/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WeanWatch;

import java.awt.Color;
import java.awt.Dimension;

import WeanWatch.controller.MetaphoricHandlerCtrl;
import WeanWatch.controller.RootCtrl;
import WeanWatch.controller.TriangleMetaphoricCtrl;
import WeanWatch.model.PDMSConn;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.Pane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Polygon;
import javafx.stage.Stage;
import java.io.FileInputStream;
import javafx.fxml.FXML;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;



import javafx.scene.paint.*;

import WeanWatch.model.*;


public class App extends Application {

    public static void main(String[] args) {
        // Launch JavaFX
        launch(args); 

        PDMSConn pdmsConn = PDMSConn.getInstance();

        pdmsConn.getPatients();

        //dispFigures(); 
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Get screen size
        Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();

        System.out.println(screenSize.getHeight());
        System.out.println(screenSize.getWidth());


        double width = screenSize.getWidth();
		double height = screenSize.getHeight();



		FXMLLoader loader = new FXMLLoader();
		loader.setLocation(App.class.getClassLoader().getResource("view/ScreeningView.fxml"));
		ScrollPane view = (ScrollPane) loader.load();

		
		TriangleMetaphoricFactory factory = new TriangleMetaphoricFactory();



		try {
			primaryStage.setScene(new Scene(factory.create(new DetectedCase()), width, height));			
			//primaryStage.setScene(new Scene(view, width, height));
			//primaryStage.getScene().getStylesheets().add("view/Stylesheet.css");
			primaryStage.show();
            
		} catch (Exception e) {
			e.printStackTrace();
		}

		//System.out.println(firstTriangle.getPoints());
        // TODO Auto-generated method stub
        
    }
}
